version: '3.8'

services:
  # Your Spring Boot Application
  app:
    build: ./  # Uses your Dockerfile
    ports:
      - "8081:8081"

  # Prometheus for metrics scraping
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    depends_on:
        - app

  # Grafana for visualization
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
