spring:
  application:
    name: Spring_Boot_Jenkins
  datasource:
      url: jdbc:h2:mem:projects
      username: sa
      password:
      driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: Spring_Boot_Jenkins
